# Generated by Django 3.0.8 on 2020-07-29 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('Population', models.IntegerField()),
                ('GDP', models.FloatField()),
                ('Pin_Code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(editable=False, max_length=100, unique=True)),
                ('Description', models.TextField()),
                ('Population', models.IntegerField()),
                ('GDP', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(editable=False, max_length=100, unique=True)),
                ('Description', models.TextField()),
                ('Population', models.IntegerField()),
                ('GDP', models.FloatField()),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('Population', models.IntegerField()),
                ('GDP', models.FloatField()),
                ('Pin_Code', models.CharField(max_length=100)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.State')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(editable=False, max_length=100, unique=True)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.City')),
                ('Town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Town')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='Country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.State'),
        ),
    ]
