# Generated by Django 3.0.8 on 2020-07-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200729_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
